//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShieldWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comentario()
        {
            this.hora = new HashSet<hora>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public bool notificar { get; set; }
        public string usuarios_id { get; set; }
        public int tarefas_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tarefa tarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hora> hora { get; set; }
    }
}
