//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShieldWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hora
    {
        public int id { get; set; }
        public string usuarios_id { get; set; }
        public float quantidade_horas { get; set; }
        public System.DateTime data { get; set; }
        public int tarefas_id { get; set; }
        public int comentarios_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual comentario comentario { get; set; }
        public virtual tarefa tarefa { get; set; }
    }
}
