//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShieldWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarefa()
        {
            this.comentario = new HashSet<comentario>();
            this.hora = new HashSet<hora>();
        }
    
        public int id { get; set; }
        public int projetos_id { get; set; }
        public string titulo { get; set; }
        public string tipo_solicitacao { get; set; }
        public string briefing { get; set; }
        public string label { get; set; }
        public string historico_tarefas { get; set; }
        public Nullable<bool> avaliacao_criticidade { get; set; }
        public Nullable<int> nivel_criticidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario> comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hora> hora { get; set; }
        public virtual projeto projeto { get; set; }
    }
}
